@echo off
setlocal

rem Путь к Git (если git не в PATH)
set "GIT_PATH=C:\Program Files\Git\bin"
if exist "%GIT_PATH%\git.exe" (
    set "PATH=%GIT_PATH%;%PATH%"
)

rem Сохраняем текущий каталог
pushd "%~dp0"

rem Получаем количество коммитов
for /f %%i in ('git rev-list --count HEAD') do (
    set "GIT_REV=%%i"
)

rem Возвращаемся назад
popd

set "OUT_DIR=%~dp0"
if not exist "%OUT_DIR%" mkdir "%OUT_DIR%"

set "TIME_HHMM=%TIME:~0,8%"

(
echo // Auto-generated by generate_version.bat
echo #ifndef VERSION_H
echo #define VERSION_H
echo #define APP_VERSION "0.%GIT_REV%.0"
echo #define BUILD_DATE "%DATE% %TIME_HHMM%"
echo #endif
) > "%OUT_DIR%\version.h"

echo [generate_version] ver 0.%GIT_REV%.0